hugo_env: &hugo_env
  BASE_URL: adresse-site-statique-s3

kind: pipeline
name: hugo-s3-deploy

steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

  - name: deploy-to-s3
    image: amazon/aws-cli:2.31.17
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION:
        from_secret: s3_region
      BUCKET:
        from_secret: s3_bucket_name
    commands:
      - aws s3 cp public/ s3://$BUCKET/ --recursive --acl public-read

    when:
      event: push
      branch: master
