hugo_env: &hugo_env
  BASE_URL: https://monsite.fr/ 

kind: pipeline
name: hugo-website-to-s3

steps:
  # 1. Étape de construction du site avec Hugo.
  # Les fichiers statiques seront générés dans le dossier 'public/'.
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env # <-- J'ai rajouté cette ligne pour définir $BASE_URL
    commands:
      # Utilise le répertoire 'public/' par défaut pour la sortie
      - hugo --baseURL $BASE_URL

  # 2. Étape de déploiement sur AWS S3.
  - name: upload-to-s3
    image: plugins/s3
    settings:
      # --- PARAMÈTRES S3 À PERSONNALISER ---
      
      # [OBLIGATOIRE] Nom de votre bucket S3 (Ex: mon-site-hugo-prod)
      bucket: bucketawss38
      
      # [OBLIGATOIRE] Région AWS de votre bucket (Ex: eu-west-3, us-east-1)
      region: us-east-1
      
      # [OBLIGATOIRE] Source : Les fichiers statiques générés par Hugo
      source: public/**/*
      
      # Cible : Uploader à la racine du bucket
      target: /
      
      # ACL : Permettre l'accès public pour l'hébergement web statique
      acl: public-read
      
      # Retire le préfixe 'public/' du chemin lors de l'upload
      strip_prefix: public/
      
      # --- SECRETS À DÉFINIR DANS DRONE ---
    secrets:
      access_key: aws_access_key_id
      secret_key: aws_secret_access_key
      
    when:
      event: push
      branch:
        - master

  # 3. Étape d'affichage des URLs (Optionnel, ajusté pour S3)
  - name: display_urls
    image: lowess/drone-tabulate
    environment:
      <<: *hugo_env # <-- J'ai rajouté cette ligne pour que $BASE_URL soit accessible
    settings:
      headers:
        - Type
        - URL
      rows:
        -
          - "S3 Endpoint"
          - http://bucketawss38.s3-ec2-54-90-192-5.compute-1.us-east-1.amazonaws.com/
        -
          - "Custom Domain"
          - $BASE_URL 
    when:
      event: push
      branch:
        - master
