kind: pipeline
name: aws_deployment_pipeline

platform:
  os: linux
  arch: amd64

steps:
  - name: deploy_to_s3
    image: plugins/s3
    settings:
      bucket:
        from_secret: s3_bucket_name
      region:
        from_secret: s3_region
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: ./dist           # dossier local à déployer
      target: /                # chemin dans le bucket
      acl: public-read         # pour rendre le site accessible publiquement
      delete: true             # supprime les fichiers qui ne sont plus présents localement

# Déclenchement typique pour les push sur la branche 'main'
trigger:
  branch:
    - main
  event:
    - push
