kind: pipeline
name: aws_deployment_pipeline

# Assure que le pipeline s'exécutera sur une architecture compatible Linux/x86_64
platform:
  os: linux
  arch: amd64

# Correct structure for your .drone.yml step
steps:
  - name: my_aws_step
    image: plugins.drone.io
    commands:
      - echo "Running deployment..."
    
    # Correct structure starts here
    environment:
      # AWS_ACCESS_KEY_ID is the key. 
      # Its value is a map (the indented block below it).
      AWS_ACCESS_KEY_ID: 
        from_secret: aws_access_key_id
      
      # AWS_SECRET_ACCESS_KEY is the key. 
      # Its value is a map (the indented block below it).
      AWS_SECRET_ACCESS_KEY: 
        from_secret: aws_secret_access_key
      
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION:
        from_secret: s3_region
      BUCKET: 
        from_secret: s3_bucket_name

# Déclenchement typique pour les push sur la branche 'main'
trigger:
  branch:
    - main
  event:
    - push