hugo_env: &hugo_env
  BASE_URL: https://ec2-107-20-91-130.compute-1.amazonaws.com/ 

kind: pipeline
name: hugo-website-aws

steps:
  # Étape 1 : Construction du site (AUCUN CHANGEMENT NÉCESSAIRE)
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      # Hugo compile le site dans le dossier 'public'
      - hugo --baseURL $BASE_URL 

  # Étape 2 : DÉPLOIEMENT VERS S3 (Remplacement de 'publish-website') 🚀
  - name: deploy-to-s3
    image: plugins/s3:latest # Utilisation du plugin S3
    settings:
      # Configuration du Bucket
      bucket: ec2-107-20-91-130.compute-1.amazonaws.com
      region: us-east-1
      source: public/                  
      target: /
      acl: public-read               
      
      # Authentification AWS (récupération des secrets configurés sur le Drone Server)
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      session_token:
        from_secret: aws_session_token 
        
    when:
      event: push
      branch: master

  # Étape 3 : Affichage des URLs (ADAPTATION)
  - name: display_urls
    image: lowess/drone-tabulate
    source: public/
    environment:
      # Assurez-vous que cette URL pointe vers votre endpoint S3
      S3_WEBSITE_URL: https://ec2-107-20-91-130.compute-1.amazonaws.com/ 
    settings:
      headers:
        - Type de Lien
        - URL du Site
      rows:
        -
          - "Endpoint S3"
          - $S3_WEBSITE_URL
    when:
      event: push
      branch: master