kind: pipeline
name: aws_deployment_pipeline

# Assure que le pipeline s'exécutera sur une architecture compatible Linux/x86_64
platform:
  os: linux
  arch: amd64

steps:
  - name: deploy_to_s3
    # L'image officielle d'AWS CLI est recommandée pour les tâches AWS.
    # Si vous devez aussi faire de la compilation, choisissez une image adaptée (ex: node, python, golang, etc.)
    image: amazon/aws-cli:latest 
    commands:
      # Les variables d'environnement sont maintenant disponibles.
      - echo "Configuration AWS réussie."
      - echo "Région S3: $AWS_DEFAULT_REGION"
      - echo "Bucket cible: $BUCKET"
      
      # Exemple d'utilisation de l'AWS CLI pour synchroniser un répertoire local (ex: 'dist') vers S3
      # - aws s3 sync ./dist s3://$BUCKET --region $AWS_DEFAULT_REGION
      
      # Exemple de vérification du bucket (vous devriez voir les fichiers s'ils existent)
      - aws s3 ls s3://$BUCKET --region $AWS_DEFAULT_REGION

    # Définition des variables d'environnement injectées depuis les secrets de Drone
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token 
      AWS_DEFAULT_REGION:
        from_secret: s3_region
      BUCKET:
        from_secret: s3_bucket_name

# Déclenchement typique pour les push sur la branche 'main'
trigger:
  branch:
    - main
  event:
    - push